### PR TITLE
Mitigation for tuple component parameters

### PR DESCRIPTION
**Pull request by 333fred**
Mitigation for https://github.com/dotnet/razor-compiler/issues/332. We were generating code that looks like `global::(Tuple, Elements)`, which is illegal. In order to properly do this rewrite, we really need to parse the type name in `TypeNameHelper` and do a rewrite using a walk, but this is currently not possible because that layer does not have roslyn access. As a temporary mitigation until that is changed, we skip rewriting tuple types.

### CODE REVIEW

**Comment by 333fred** [comment]
@chsienki @dotnet/razor-compiler for review.

**Review by chsienki — APPROVED** [review]
LGTM. Can we also port it over to razor-tooling?

**Comment by 333fred** [comment]
> LGTM. Can we also port it over to razor-tooling?

I figured I would after this was merged.

**Comment by 333fred** [comment]
@dotnet/razor-compiler for a second review.

**Review by jaredpar — APPROVED** [review]

**Pull request merged**
