### PR TITLE
Update branding to 6.0.4

### PR DESCRIPTION
**Pull request by vseanreesermsft**

### CODE REVIEW

**Comment by dougbu** [comment]
I may be wrong about needing branding updates here. @pranavkm what is the right policy for this branch❔

**Comment by pranavkm** [comment]
So far we've been branching with the SDK. That said, I'm not super sure if we have any planned work for this 6.0.4xx, so it might not be necessary to continue doing this?

**Comment by dougbu** [comment]
@pranavkm my point was about branding, not creating new branches. If we have been fine w/ non-stable branding and leaving the prerelease version alone, we shouldn't need PRs like this one. So, have we done anything similar since branching release/6.0.2xx❔

If not, we can close this PR and #83. My thinks to @vseanreesermsft -- especially if this was unnecessary.

**Comment by pranavkm** [comment]
>  If we have been fine w/ non-stable branding and leaving the prerelease version alone, we shouldn't need PRs like this one.

I would think so. @TanayParikh / @javiercn in case you feel differently.

**Comment by TanayParikh** [comment]
> > If we have been fine w/ non-stable branding and leaving the prerelease version alone, we shouldn't need PRs like this one.
> 
> I would think so. @TanayParikh / @javiercn in case you feel differently.

Yeah given we aren't planning any immediate work here, I think it may be fine to leave it alone.

**Comment by dougbu** [comment]
Thanks again @vseanreesermsft

**Pull request closed without merging**
